/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as betting from "./Betting";
export type { betting };
import type * as test from "./test";
export type { test };
import type * as utils from "./utils";
export type { utils };
export type { APIConsumer } from "./APIConsumer";
export type { KeepersCounter } from "./KeepersCounter";
export type { PriceConsumerV3 } from "./PriceConsumerV3";
export type { RandomNumberConsumerV2 } from "./RandomNumberConsumerV2";
